### ISSUE TITLE
Global Backpacks Broken

### ISSUE THREAD

**Issue by Giacomino99** [Oliver-makes-code/server-backpacks#3]
Minecraft Version: 1.18.1

Firstly, I cannot find any documentation about how the Global Backpack is meant to work.

When using the Global Backpack, the GUI opens and I am able to place an item inside. When closing and reopening there is no item in the backpack. Additionally, whenever I open a Global Backpack there is the following error in the log:

```
java.lang.NullPointerException: null
  at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
  at net.minecraft.class_1703.method_7623(class_1703.java:167) ~[client-intermediary.jar:?]
  at eu.pb4.sgui.virtual.inventory.VirtualScreenHandler.method_7623(VirtualScreenHandler.java:86) ~[sgui-1.0.0-rc6+1.18-pre5-364a64ea5786f97b.jar:?]
  at net.minecraft.class_1703.method_7596(class_1703.java:131) ~[client-intermediary.jar:?]
  at net.minecraft.class_3222.method_14235(class_3222.java:401) ~[client-intermediary.jar:?]
  at net.minecraft.class_3222.method_17355(class_3222.java:1040) ~[client-intermediary.jar:?]
  at eu.pb4.sgui.api.gui.SimpleGui.sendGui(SimpleGui.java:169) ~[sgui-1.0.0-rc6+1.18-pre5-364a64ea5786f97b.jar:?]
  at eu.pb4.sgui.api.gui.SimpleGui.open(SimpleGui.java:202) ~[sgui-1.0.0-rc6+1.18-pre5-364a64ea5786f97b.jar:?]
  at olivermakesco.de.servback.GlobalBackpackGui.<init>(GlobalBackpackGui.java:15) ~[servback-1.21.12.jar:?]
  at olivermakesco.de.servback.GlobalBackpackItem.method_7836(GlobalBackpackItem.java:30) ~[servback-1.21.12.jar:?]
  at net.minecraft.class_1799.method_7913(class_1799.java:252) ~[client-intermediary.jar:?]
  at net.minecraft.class_3225.method_14256(class_3225.java:282) ~[client-intermediary.jar:?]
  at net.minecraft.class_3244.method_12065(class_3244.java:1093) ~[client-intermediary.jar:?]
  at net.minecraft.class_2886.method_12550(class_2886.java:25) ~[client-intermediary.jar:?]
  at net.minecraft.class_2886.method_11054(class_2886.java:7) ~[client-intermediary.jar:?]
  at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[client-intermediary.jar:?]
  at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
  at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[client-intermediary.jar:?]
  at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
  at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780) ~[client-intermediary.jar:?]
  at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162) ~[client-intermediary.jar:?]
  at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[client-intermediary.jar:?]
  at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762) ~[client-intermediary.jar:?]
  at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756) ~[client-intermediary.jar:?]
  at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[client-intermediary.jar:?]
  at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:741) ~[client-intermediary.jar:?]
  at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688) ~[client-intermediary.jar:?]
  at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
  at java.lang.Thread.run(Thread.java:833) [?:?]
```

All other backpacks seem to function normally.

**Comment by Oliver-makes-code** [comment]
Hm.. I'll look into this

**Comment by Oliver-makes-code** [comment]
Fixed in the latest commit
